# Generated by Django 2.0.1 on 2018-01-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Askstories',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descendants', models.CharField(max_length=70)),
                ('by', models.CharField(max_length=70)),
                ('type', models.CharField(max_length=70)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Jobstories',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descendants', models.CharField(max_length=70)),
                ('by', models.CharField(max_length=70)),
                ('type', models.CharField(max_length=70)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Newstories',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descendants', models.CharField(max_length=70)),
                ('by', models.CharField(max_length=70)),
                ('type', models.CharField(max_length=70)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Showstories',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descendants', models.CharField(max_length=70)),
                ('by', models.CharField(max_length=70)),
                ('type', models.CharField(max_length=70)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
