# Generated by Django 2.0.1 on 2018-01-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parser', '0003_auto_20180122_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstories',
            name='kids',
            field=models.TextField(default='kids'),
        ),
        migrations.AddField(
            model_name='jobstories',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobstories',
            name='text',
            field=models.TextField(default='text'),
        ),
        migrations.AddField(
            model_name='jobstories',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobstories',
            name='title',
            field=models.TextField(default='title'),
        ),
        migrations.AddField(
            model_name='newstories',
            name='kids',
            field=models.TextField(default='kids'),
        ),
        migrations.AddField(
            model_name='newstories',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newstories',
            name='text',
            field=models.TextField(default='text'),
        ),
        migrations.AddField(
            model_name='newstories',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newstories',
            name='title',
            field=models.TextField(default='title'),
        ),
        migrations.AddField(
            model_name='showstories',
            name='kids',
            field=models.TextField(default='kids'),
        ),
        migrations.AddField(
            model_name='showstories',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='showstories',
            name='text',
            field=models.TextField(default='text'),
        ),
        migrations.AddField(
            model_name='showstories',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='showstories',
            name='title',
            field=models.TextField(default='title'),
        ),
        migrations.AlterField(
            model_name='askstories',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
