# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=200)),
                ('email_user', models.EmailField(max_length=100)),
                ('total_price', models.FloatField()),
                ('total_count', models.IntegerField()),
                ('product_ids', models.CharField(max_length=200)),
                ('product_fk', models.ManyToManyField(to='product.Product')),
            ],
        ),
    ]
