# Generated by Django 2.0.1 on 2018-01-28 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Message')),
            ],
        ),
        migrations.RemoveField(
            model_name='mood',
            name='message',
        ),
        migrations.DeleteModel(
            name='Mood',
        ),
    ]
